version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    target-branch: "main"
    allow:
      - dependency-type: direct
